export default {
    // ACCOUNT
    CREATION_ACCOUNT: "CREATION_ACCOUNT",
    CREATION_ACCOUNT_RESPONSE: "CREATION_ACCOUNT_RESPONSE",
    SIGN_UP_ACCOUNT: "SIGN_UP_ACCOUNT",
    SIGN_IN_ACCOUNT: "SIGN_IN_ACCOUNT",
    ACCOUNT_BY_TOKEN: "ACCOUNT_BY_TOKEN",
    ACCOUNT_REQUEST: "ACCOUNT_REQUEST",
    ACCOUNT_RESPONSE: "ACCOUNT_RESPONSE",
    ACCOUNT_ERROR: "ACCOUNT_ERROR",
    LOGIN_ACCOUNT: "LOGIN_ACCOUNT",

    // WORKERS
    FETCH_WORKERS: "FETCH_WORKERS",
    WORKERS_REQUEST: "WORKERS_REQUEST",
    WORKERS_RESPONSE: "WORKERS_RESPONSE",
    WORKERS_ERROR: "WORKERS_ERROR",
    CREATION_WORKER: "CREATION_WORKER",
    CREATION_WORKER_RESPONSE: "CREATION_WORKER_RESPONSE",
};
