export default {
    // ACCOUNT
    CREATION_ACCOUNT: "CREATION_ACCOUNT",
    CREATION_ACCOUNT_RESPONSE: "CREATION_ACCOUNT_RESPONSE",
    SIGN_UP_ACCOUNT: "SIGN_UP_ACCOUNT",
    SIGN_IN_ACCOUNT: "SIGN_IN_ACCOUNT",
    ACCOUNT_BY_TOKEN: "ACCOUNT_BY_TOKEN",
    ACCOUNT_REQUEST: "ACCOUNT_REQUEST",
    ACCOUNT_RESPONSE: "ACCOUNT_RESPONSE",
    ACCOUNT_ERROR: "ACCOUNT_ERROR",
  /*  FETCH_ACCOUNT_BY_ID: "FETCH_ACCOUNT_BY_ID",
    DOWNLOAD_FILE: "DOWNLOAD_FILE",

    ACCOUNT_BY_REQUEST: "ACCOUNT_REQUEST",
    ACCOUNT_BY_RESPONSE: "ACCOUNT_RESPONSE",
    ACCOUNT_BY_ERROR: "ACCOUNT_ERROR",

    LOGIN_FETCH_ACCOUNT: "LOGIN_FETCH_ACCOUNT",
    GET_ACCOUNT_BY_TOKEN: "GET_ACCOUNT_BY_TOKEN",

    // CONTEST
    FETCH_CONTEST: "FETCH_CONTEST",
    FETCH_CONTESTS_BY_CUSTOMER_ID: "FETCH_CONTESTS_BY_CUSTOMER_ID",
    FETCH_CONTEST_BY_ID: "FETCH_CONTEST_BY_ID",
    UPDATE_CONTEST_BY_ID: "UPDATE_CONTEST_BY_ID",
    CONTEST_REQUEST: "CONTEST_REQUEST",
    CONTEST_RESPONSE: "CONTEST_RESPONSE",
    CONTEST_ERROR: "CONTEST_ERROR",
    ONE_CONTEST_REQUEST: "CONTEST_REQUEST",
    ONE_CONTEST_RESPONSE: "CONTEST_RESPONSE",
    ONE_CONTEST_ERROR: "CONTEST_ERROR",
    CREATE_CONTEST: "CREATE_CONTEST",
    UPLOAD_FILES: "UPLOAD_FILES",
    FILE_REQUEST: "FILE_REQUEST",
    FILE_RESPONSE: "FILE_RESPONSE",
    CHOICE_TYPE_CONTEST: "CHOICE_TYPE_CONTEST",
    CONTEST_STEP_RESPONSE: "CONTEST_STEP_RESPONSE",
    CONTEST_CREATION_RESPONSE: "CONTEST_CREATION_RESPONSE",
    NEXT_STEP_CREATION_CONTEST: "NEXT_STEP_CREATION_CONTEST",
    PREV_STEP_CREATION_CONTEST: "PREV_STEP_CREATION_CONTEST",
    CHANGE_CREATION_CONTEST: "CHANGE_CREATION_CONTEST",

    // REQUEST
    UPDATE_REQUEST_BY_ID: "UPDATE_REQUEST_BY_ID",
    REQUEST_REQUEST: "CONTEST_REQUEST",
    REQUEST_RESPONSE: "CONTEST_RESPONSE",
    REQUEST_ERROR: "CONTEST_ERROR",
    ACCEPTED_REQUEST: "ACCEPTED_REQUEST",
    REJECTED_REQUEST: "REJECTED_REQUEST",

    // CONVERSATIONS

    ALL_CONVERSATIONS: "ALL_CONVERSATIONS",
    CONVERSATION_BY_ID: "CONVERSATION_BY_ID",
    CREATE_CONVERSATION: "CREATE_CONVERSATION",
    CREATE_MESSAGE: "CREATE_MESSAGE",
    MESSAGE_ADDED: "MESSAGE_ADDED",
    MESSAGE_RESPONSE: "MESSAGE_RESPONSE",

    CONVERSATIONS_REQUEST: "CONVERSATIONS_REQUEST",
    CONVERSATIONS_RESPONSE: "CONVERSATIONS_RESPONSE",
    CONVERSATIONS_ERROR: "CONVERSATIONS_ERROR"*/
};
