export default {
    // ACCOUNT
    CREATION_ACCOUNT: "CREATION_ACCOUNT",
    CREATION_ACCOUNT_RESPONSE: "CREATION_ACCOUNT_RESPONSE",
    REMOVE_ACCOUNT: "REMOVE_ACCOUNT",
    SIGN_UP_ACCOUNT: "SIGN_UP_ACCOUNT",
    SIGN_IN_ACCOUNT: "SIGN_IN_ACCOUNT",
    ACCOUNT_BY_TOKEN: "ACCOUNT_BY_TOKEN",
    ACCOUNT_REQUEST: "ACCOUNT_REQUEST",
    ACCOUNT_RESPONSE: "ACCOUNT_RESPONSE",
    ACCOUNT_ERROR: "ACCOUNT_ERROR",
    LOGIN_ACCOUNT: "LOGIN_ACCOUNT",
    UPDATE_ACCOUNT: "UPDATE_ACCOUNT",

    // WORKERS
    FETCH_WORKERS: "FETCH_WORKERS",
    WORKERS_REQUEST: "WORKERS_REQUEST",
    WORKERS_RESPONSE: "WORKERS_RESPONSE",
    WORKERS_ERROR: "WORKERS_ERROR",
    CREATION_WORKER: "CREATION_WORKER",
    CREATION_WORKER_RESPONSE: "CREATION_WORKER_RESPONSE",
    SEARCH_FETCH_WORKERS: "SEARCH_FETCH_WORKERS",

    // WORKER
    FETCH_WORKER: "FETCH_WORKER",
    PUT_FETCH_WORKER: "PUT_FETCH_WORKER",
    WORKER_REQUEST: "WORKER_REQUEST",
    WORKER_RESPONSE: "WORKER_RESPONSE",
    WORKER_ERROR: "WORKER_ERROR",
    DELETE_FETCH_WORKER: "DELETE_FETCH_WORKER",
    // MODAL FORM
    PUT_WORKER_MODAL_FORM: "PUT_WORKER_MODAL_FORM",
    PUT_WORKER_MODAL_FORM_OPEN: "PUT_WORKER_MODAL_FORM_OPEN",
    PUT_WORKER_MODAL_FORM_CLOSE: "PUT_WORKER_MODAL_FORM_CLOSE",
    QUEST_REMOVE_ACCOUNT_MODAL_FORM: "QUEST_REMOVE_ACCOUNT_MODAL_FORM",
    QUEST_OPEN_MODAL_FORM: "QUEST_OPEN_MODAL_FORM",
    QUEST_CLOSE_MODAL_FORM: "QUEST_CLOSE_MODAL_FORM",
};
